package distributed.chat.server.model.message;

public enum MessageType {
    NEW_IDENTITY,
    RESERVE_IDENTITY,
    RESERVE_IDENTITY_RESPONSE,
    RESERVE_IDENTITY_CONFIRM,
    RESERVE_IDENTITY_CONFIRM_RESPONSE,
    ADD_IDENTITY,
    ADD_IDENTITY_RESPONSE,

    LIST,
    WHO,

    ROOM_CHANGE,
    ROOM_LIST,
    ROOM_CONTENTS,


    JOIN_ROOM,
    ROUTE,
    MOVE_JOIN,
    SERVER_CHANGE,
    DELETE_ROOM,
    MESSAGE,
    MESSAGE_RESPONSE,
    QUIT,

    CREATE_ROOM,
    RESERVE_ROOM,
    RESERVE_ROOM_RESPONSE,
    RESERVE_ROOM_CONFIRM,
    RESERVE_ROOM_CONFIRM_RESPONSE,
    ADD_ROOM, // Todo
    ADD_ROOM_RESPONSE, // Todo

    DELETE_IDENTITY, // Todo

    HEARTBEAT, // TODO

    I_AM_UP,
    VIEW,
    COORDINATOR,
    ELECTION,
    ANSWER,
    NOMINATION,

    SYNC_GLOBAL_LISTS

}
